# Generated by Django 3.2.9 on 2023-07-20 11:59

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_remove_performance_company'),
        ('operatick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperaPerformance',
            fields=[
                ('performance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='performance.performance')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.company')),
            ],
            bases=('performance.performance',),
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
