# Generated by Django 3.2.9 on 2023-07-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operatick', '0002_operaperformance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperaPerformance',
        ),
    ]
